### ISSUE TITLE
2.0-beta01: Error when migrating from 1.3.1

### ISSUE THREAD

**Issue by mathieui** [readrops/Readrops#191]
Version: 2.0-beta01 from FDroid
Android version: 14 (Lineage 21)

This is for a FreshRSS account, not sure if this is related, but I am adding it.

When installing the 2.0 version from FDroid, I could see the items fetched in version 1.3.1 in the past, but I could no longer refresh the feeds, with a toast coming up every time with the message "Exception: null".

Additionally, I got the following traceback when going into the account parameters (with the error screen, etc):
```
org.koin.core.error.InstanceCreationException: Could not create instance for '[Factory:'com.readrops.app.account.credentials.AccountCredentialsScreenModel']'
	at org.koin.core.instance.InstanceFactory.create(SourceFile:185)
	at org.koin.core.instance.FactoryInstanceFactory.get(SourceFile:1)
	at org.koin.core.scope.Scope.resolveInstance(SourceFile:109)
	at org.koin.core.scope.Scope.get(SourceFile:127)
	at com.readrops.app.account.credentials.AccountCredentialsScreen.Content(SourceFile:256)
	at cafe.adriel.voyager.transitions.ComposableSingletons$SlideTransitionKt$lambda-2$1.invoke(SourceFile:24)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:17)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:20)
	at androidx.compose.material3.AppBarKt$BottomAppBar$6.invoke(SourceFile:66)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:13)
	at androidx.compose.runtime.Updater.CompositionLocalProvider(SourceFile:23)
	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SourceFile:96)
	at androidx.compose.material3.AppBarKt$BottomAppBar$6.invoke(SourceFile:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:13)
	at org.koin.compose.KoinApplicationKt$KoinContext$1.invoke(SourceFile:37)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:13)
	at org.koin.compose.KoinApplicationKt$KoinContext$1.invoke(SourceFile:111)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:13)
	at androidx.compose.runtime.Updater.CompositionLocalProvider(SourceFile:43)
	at androidx.paging.HintHandler$forceSetHint$2.invoke(SourceFile:254)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:13)
	at androidx.compose.runtime.Updater.CompositionLocalProvider(SourceFile:23)
	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SourceFile:96)
	at cafe.adriel.voyager.navigator.Navigator$saveableState$1.invoke(SourceFile:185)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:17)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:20)
	at androidx.compose.foundation.lazy.LazyListIntervalContent$item$3.invoke(SourceFile:87)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:17)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:20)
	at cafe.adriel.voyager.androidx.AndroidScreenLifecycleOwner.ProvideBeforeScreenContent(SourceFile:33)
	at cafe.adriel.voyager.core.lifecycle.DisposableEffectKt.RecursiveProvideBeforeScreenContent(SourceFile:265)
	at androidx.compose.animation.CrossfadeKt$Crossfade$5$1.invoke(SourceFile:130)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:13)
	at org.koin.compose.KoinApplicationKt$KoinContext$1.invoke(SourceFile:74)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:13)
	at cafe.adriel.voyager.core.lifecycle.DefaultScreenLifecycleOwner.ProvideBeforeScreenContent(SourceFile:50)
	at cafe.adriel.voyager.core.lifecycle.DisposableEffectKt.RecursiveProvideBeforeScreenContent(SourceFile:220)
	at cafe.adriel.voyager.core.lifecycle.DisposableEffectKt.MultipleProvideBeforeScreenContent(SourceFile:55)
	at cafe.adriel.voyager.navigator.Navigator.saveableState(SourceFile:227)
	at cafe.adriel.voyager.transitions.ScreenTransitionKt$ScreenTransition$9.invoke(SourceFile:97)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:17)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:20)
	at androidx.compose.foundation.text.TextFieldCursorKt$cursor$1.invoke(SourceFile:878)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:19)
	at androidx.compose.animation.Scale.AnimatedEnterExitImpl(SourceFile:1214)
	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1.invoke(SourceFile:369)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:13)
	at androidx.compose.animation.Scale.AnimatedContent(SourceFile:69)
	at androidx.compose.animation.Scale.AnimatedContent(Unknown Source:160)
	at androidx.room.Room.ScreenTransition(SourceFile:224)
	at cafe.adriel.voyager.transitions.ScreenTransitionKt$ScreenTransition$10.invoke(SourceFile:30)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(SourceFile:483)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(SourceFile:58)
	at androidx.compose.runtime.ComposerImpl.doCompose(SourceFile:158)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(SourceFile:29)
	at androidx.compose.runtime.CompositionImpl.recompose(SourceFile:35)
	at androidx.compose.runtime.Recomposer.access$performRecompose(SourceFile:123)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(SourceFile:377)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(SourceFile:34)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(SourceFile:48)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1404)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
	at android.view.Choreographer.doFrame(Choreographer.java:941)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

Clearing data & cache for the app made it possible to enter my credentials anew and everything seems to work now.

**Comment by Shinokuni** [comment]
Fixed in ee931abc1734dc36e3e19bb9e6c5b75f5ab5e23b and be865aa7f9ec8072d44606a6c1de3dab74d31e70, thanks for reporting! I will try to make the next beta also available on F-Droid.
