### ISSUE TITLE
Error on Fever setup 2.0-beta02

### ISSUE THREAD

**Issue by w1n5l0w** [readrops/Readrops#200]
After inserting the URL and credentials I'll get this error message. Cleaning cash and/or storage doesn't make a difference.

```
org.koin.core.error.InstanceCreationException: Could not create instance for '[Factory:'com.readrops.app.repositories.BaseRepository']'
	at org.koin.core.instance.InstanceFactory.create(SourceFile:185)
	at org.koin.core.instance.FactoryInstanceFactory.get(SourceFile:1)
	at org.koin.core.scope.Scope.resolveInstance(SourceFile:109)
	at org.koin.core.scope.Scope.get(SourceFile:127)
	at com.readrops.app.AppModuleKt$$ExternalSyntheticLambda17.invoke(SourceFile:546)
	at androidx.compose.runtime.Recomposer$effectJob$1$1.invoke(SourceFile:1007)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(SourceFile:133)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.JobKt.resume(SourceFile:79)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(SourceFile:105)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(SourceFile:33)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(SourceFile:17)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SourceFile:51)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SourceFile:32)
	at androidx.compose.foundation.AbstractClickablePointerInputNode.onPointerEvent-H0pRuoY(Unknown Source:2)
	at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Unknown Source:4)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:157)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:136)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:136)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:136)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:136)
	at retrofit2.OkHttpCall$1.dispatchChanges(SourceFile:36)
	at androidx.compose.material.ripple.StateLayer.process-BIzXfog(SourceFile:138)
	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(SourceFile:81)
	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(SourceFile:214)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(SourceFile:76)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3125)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2806)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3125)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2806)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3125)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2806)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3125)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2806)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:496)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1952)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4510)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:454)
	at android.view.View.dispatchPointerEvent(View.java:16548)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7559)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7326)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6723)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6780)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6746)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6912)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6754)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6969)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6727)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6780)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6746)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6754)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6727)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9827)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9778)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9747)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9969)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:295)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:349)
	at android.os.Looper.loopOnce(Looper.java:189)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

```

**Comment by Shinokuni** [comment]
I am able to reproduce when avoiding putting a / at the end of the URL. I wasn't able to do so with a very long password. Could you try authenticating with an URL without end /?

**Comment by Shinokuni** [comment]
I've pushed a fix in 2.0.1. Could you tell me if it happens again or not for you?
