### ISSUE TITLE
[Bug] Crash at start

### ISSUE THREAD

**Issue by pp-r** [readrops/Readrops#206]
**Describe the bug**
Since update from v1.3 to v2.0, app crash and can't be opened.

**To Reproduce**
1. Update to v2.0
3. Try to open app
4. App crash and can't be opened

**Expected behavior**
App should open.

**Environment information (please complete the following information):**
 - Account type: [FreshRSS]
 - App version: [2.0]
 - Android version: [Android 10]
 - Device type: [Huawei Mate 10 Pro]
 - Store: [F-Droid apk]
 - [x] Stacktrace collected from crash screen
 ```
java.lang.NullPointerException
	at com.readrops.app.timelime.drawer.TimelineDrawerKt$TimelineDrawer$1$2$5.invoke(SourceFile:117)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:13)
	at androidx.compose.runtime.Updater.CompositionLocalProvider(SourceFile:23)
	at com.readrops.app.timelime.drawer.DrawerFeedItemKt$DrawerFeedItem$1.invoke(SourceFile:174)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:13)
	at androidx.compose.material3.AnchoredDragScope$-CC.m(SourceFile:73)
	at androidx.compose.material3.SurfaceKt$Surface$5.invoke(SourceFile:200)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:13)
	at androidx.compose.runtime.Updater.CompositionLocalProvider(SourceFile:43)
	at androidx.compose.material3.SurfaceKt.Surface-d85dljk(SourceFile:10)
	at okio.Okio.DrawerFeedItem(SourceFile:233)
	at com.readrops.app.timelime.drawer.TimelineDrawerKt$TimelineDrawer$1.invoke(SourceFile:488)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:19)
	at androidx.paging.HintHandler$forceSetHint$2.invoke(SourceFile:1112)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:13)
	at androidx.compose.material3.AnchoredDragScope$-CC.m(SourceFile:73)
	at androidx.compose.material3.SurfaceKt$Surface$1.invoke(SourceFile:183)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:13)
	at androidx.compose.runtime.Updater.CompositionLocalProvider(SourceFile:43)
	at androidx.compose.material3.SurfaceKt.Surface-T9BRK9s(SourceFile:142)
	at androidx.compose.material3.NavigationDrawerKt.DrawerSheet-vywBR7E(SourceFile:257)
	at androidx.compose.material3.NavigationDrawerKt.ModalDrawerSheet-afqeVBk(SourceFile:259)
	at kotlin.text.CharsKt.TimelineDrawer(SourceFile:141)
	at com.readrops.app.timelime.TimelineTab$Content$16.invoke(SourceFile:135)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:13)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(SourceFile:483)
	at androidx.compose.runtime.ComposerImpl.skipToGroupEnd(SourceFile:29)
	at androidx.compose.material3.NavigationDrawerKt.ModalNavigationDrawer-FHprtrg(SourceFile:96)
	at com.readrops.app.timelime.TimelineTab.Content(SourceFile:1127)
	at com.readrops.app.more.MoreTab$$ExternalSyntheticLambda7.invoke(SourceFile:72)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(SourceFile:483)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(SourceFile:58)
	at androidx.compose.runtime.ComposerImpl.doCompose(SourceFile:158)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(SourceFile:29)
	at androidx.compose.runtime.CompositionImpl.recompose(SourceFile:35)
	at androidx.compose.runtime.Recomposer.access$performRecompose(SourceFile:123)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(SourceFile:377)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(SourceFile:34)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(SourceFile:48)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1278)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
	at android.view.Choreographer.lambda$new$0$Choreographer(Choreographer.java:235)
	at android.view.-$$Lambda$Choreographer$zXV0PrqwmpdPajenUBozqc6c8Hs.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)] 
```
**Additional context**

**Comment by Shinokuni** [comment]
I wasn't able to reproduce but I pushed a fix guessing which fields could cause a NPE. Could you try out 2.0.1 and tell me if you still got the crash?

**Comment by pp-r** [comment]
I've updated to v2.0.1 from Play Store and no more crash at start :-)
Thanks !
