### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by WhiteNight121** [readrops/Readrops#208]
**Describe the bug**

**To Reproduce**

Open the app

**Expected behavior**

Open crashes on open

**Environment information (please complete the following information):**
 - Account type: [e.g. Freshrss, Nextcloud News]
Freshrss

 - App version: [e.g. 2.0]

Newest I think

 - Android version: [e.g. Android 13, 14]

13

 - Device type: [e.g. One Plus 12, Samsung Galaxy S23]

Google 4 5g

 - Store: [e.g F-Droid, Play Store, standalone apk]
F-Droid

 - [ ] Stacktrace collected from crash screen

java.lang.IllegalArgumentException: Unknown account type
	at kotlin.UnsignedKt.toCredentials(SourceFile:31)
	at androidx.paging.ChannelFlowCollector.emit(SourceFile:32)
	at kotlinx.coroutines.flow.DistinctFlowImpl$collect$2.emit(SourceFile:763)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SourceFile:5)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SourceFile:10)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SourceFile:1)
	at kotlinx.coroutines.flow.FlowKt.emitAllImpl$FlowKt__ChannelsKt(SourceFile:130)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(SourceFile:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:96)
	at androidx.work.Worker$2.run(SourceFile:32)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:96)

**Additional context**
Add any other context about the problem here

Started to day as far as I know as I use the app everyday.

Thanks love the app

**Comment by WhiteNight121** [comment]
Uninstalled and reinstalled fixed it
