### ISSUE TITLE
Crash immediately on open v2.0.1

### ISSUE THREAD

**Issue by pratikashwekar** [readrops/Readrops#218]
java.lang.IllegalArgumentException: Unknown account type
	at kotlin.UnsignedKt.toCredentials(SourceFile:31)
	at androidx.paging.ChannelFlowCollector.emit(SourceFile:32)
	at kotlinx.coroutines.flow.DistinctFlowImpl$collect$2.emit(SourceFile:763)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SourceFile:5)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SourceFile:10)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SourceFile:1)
	at kotlinx.coroutines.flow.FlowKt.emitAllImpl$FlowKt__ChannelsKt(SourceFile:130)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(SourceFile:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:96)
	at androidx.work.Worker$2.run(SourceFile:32)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:96)

**Comment by iamnimnul** [comment]
Same here

```
java.lang.IllegalArgumentException: Unknown account type
	at kotlin.UnsignedKt.toCredentials(SourceFile:31)
	at androidx.paging.ChannelFlowCollector.emit(SourceFile:32)
	at kotlinx.coroutines.flow.DistinctFlowImpl$collect$2.emit(SourceFile:763)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SourceFile:5)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SourceFile:10)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SourceFile:1)
	at kotlinx.coroutines.flow.FlowKt.emitAllImpl$FlowKt__ChannelsKt(SourceFile:130)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(SourceFile:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:96)
	at androidx.work.Worker$2.run(SourceFile:32)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:96)
```

**Comment by sevmonster** [comment]
https://github.com/readrops/Readrops/issues/214#issuecomment-2373623897

**Comment by Shinokuni** [comment]
As sevmonster said, did you start using Readrops with first 2.0 beta? If yes, then it's a known issue and there is nothing you can do apart from wiping data and recreating your account, as stated in the release notes.
