### ISSUE TITLE
crash log

### ISSUE THREAD

**Issue by talkingseedling** [readrops/Readrops#220]
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=data: (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2252)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1878)
	at android.app.Activity.startActivityForResult(Activity.java:5760)
	at androidx.activity.ComponentActivity.startActivityForResult(SourceFile:2)
	at android.app.Activity.startActivity(Activity.java:6212)
	at com.readrops.app.item.ItemScreen.access$Content$openUrl(SourceFile:186)
	at com.readrops.app.item.ItemScreen$Content$6$$ExternalSyntheticLambda3.invoke(SourceFile:30)
	at com.readrops.app.item.view.ItemWebView$1.shouldOverrideUrlLoading(Unknown Source:4)
	at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:83)
	at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-TrichromeWebViewGoogle6432.aab-stable-666810033:124)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:187)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

This is caused when viewing https://australiancybersecuritymagazine.com.au/keeping-to-the-basics-in-the-shadow-world-of-cybersecurity/ from their RSS feed after it's been processed by fivefilters. It's not caused when viewing other articles from the same feed. Trying the same article again reproduces the crash.

Readrops 2.0.1 from GitHub.

**Comment by Shinokuni** [comment]
What account type are you using? I'm currently not able to reproduce with both base feed and FiveFilters generated one with a local account. 

Did the crash occur when clicking on an item in TimelineTab or opening an item url/url in item text?

**Comment by Shinokuni** [comment]
If you are using a self-hosted instance of fivefilters, could you give me the generated file of `/makefulltextfeed.php`? Then I will be able to test it in a more accurate way.

**Comment by talkingseedling** [comment]
[Australian Cyber Security Magazine (full-text feed).txt](https://github.com/user-attachments/files/17687669/Australian.Cyber.Security.Magazine.full-text.feed.txt)

Had to rename .html to .txt so github would allow the upload.

**Comment by Shinokuni** [comment]
Oh yeah thanks but I was talking about the generated RSS feed 😆
